import type {
    NewsGroupId,
    NewsLanguage,
} from "@entities/news/model/news.types";

export type NewsSourceType = "rss" | "hackernews" | "github-trending";

export interface NewsSource {
    id: string;
    name: string;
    type: NewsSourceType;
    /** 화면에서 묶이는 그룹 */
    group: NewsGroupId;
    url: string;
    /** 1-10. 점수 계산의 기본 가중치 */
    weight: number;
    language: NewsLanguage;
}

/**
 * 수집 대상 목록. **API 키가 필요한 소스는 넣지 않는다** — 전부 공개 RSS/HTML/공개 API다.
 *
 * 제외한 것:
 *   - Reddit — OAuth 클라이언트 필요
 *   - YouTube 채널 Atom(`/feeds/videos.xml`) — 2026년 기준 404. Data API 키가 있어야 한다
 */
export const NEWS_SOURCES: NewsSource[] = [
    /* ── 프레임워크·플랫폼 공식 ─────────────────────────── */
    {
        id: "react-blog",
        name: "React Blog",
        type: "rss",
        group: "framework",
        url: "https://react.dev/rss.xml",
        weight: 10,
        language: "en",
    },
    {
        id: "nextjs-blog",
        name: "Next.js Blog",
        type: "rss",
        group: "framework",
        url: "https://nextjs.org/feed.xml",
        weight: 10,
        language: "en",
    },
    {
        id: "typescript-blog",
        name: "TypeScript Blog",
        type: "rss",
        group: "framework",
        url: "https://devblogs.microsoft.com/typescript/feed/",
        weight: 9,
        language: "en",
    },
    {
        id: "nodejs-blog",
        name: "Node.js Blog",
        type: "rss",
        group: "framework",
        url: "https://nodejs.org/en/feed/blog.xml",
        weight: 7,
        language: "en",
    },
    {
        id: "tailwind-blog",
        name: "Tailwind CSS Blog",
        type: "rss",
        group: "framework",
        url: "https://tailwindcss.com/feeds/feed.xml",
        weight: 8,
        language: "en",
    },
    {
        id: "web-dev",
        name: "web.dev",
        type: "rss",
        group: "framework",
        url: "https://web.dev/feed.xml",
        weight: 8,
        language: "en",
    },

    /* ── 국내 기술 블로그 ──────────────────────────────── */
    {
        id: "toss-tech",
        name: "토스 기술 블로그",
        type: "rss",
        group: "korean",
        url: "https://toss.tech/rss.xml",
        weight: 9,
        language: "ko",
    },
    {
        id: "woowahan-tech",
        name: "우아한형제들",
        type: "rss",
        group: "korean",
        url: "https://techblog.woowahan.com/feed/",
        weight: 8,
        language: "ko",
    },
    {
        id: "kakao-tech",
        name: "카카오 기술블로그",
        type: "rss",
        group: "korean",
        url: "https://tech.kakao.com/feed/",
        weight: 7,
        language: "ko",
    },
    {
        id: "kakaoent-fe",
        name: "카카오엔터 FE",
        type: "rss",
        group: "korean",
        url: "https://tech.kakaoent.com/rss.xml",
        weight: 8,
        language: "ko",
    },
    {
        id: "naver-d2",
        name: "NAVER D2",
        type: "rss",
        group: "korean",
        url: "https://d2.naver.com/d2.atom",
        weight: 7,
        language: "ko",
    },
    {
        id: "line-engineering",
        name: "LINE Engineering",
        type: "rss",
        group: "korean",
        url: "https://techblog.lycorp.co.jp/ko/feed/index.xml",
        weight: 7,
        language: "ko",
    },
    {
        id: "daangn-tech",
        name: "당근 기술 블로그",
        type: "rss",
        group: "korean",
        url: "https://medium.com/feed/daangn",
        weight: 7,
        language: "ko",
    },
    {
        id: "banksalad-tech",
        name: "뱅크샐러드",
        type: "rss",
        group: "korean",
        url: "https://blog.banksalad.com/rss.xml",
        weight: 6,
        language: "ko",
    },
    {
        id: "oliveyoung-tech",
        name: "올리브영 테크블로그",
        type: "rss",
        group: "korean",
        url: "https://oliveyoung.tech/rss.xml",
        weight: 6,
        language: "ko",
    },
    {
        id: "toast-ui",
        name: "Toast UI",
        type: "rss",
        group: "korean",
        url: "https://ui.toast.com/rss",
        weight: 7,
        language: "ko",
    },
    {
        id: "blog-jbee",
        name: "JBEE",
        type: "rss",
        group: "korean",
        url: "https://jbee.io/rss.xml",
        weight: 8,
        language: "ko",
    },
    {
        id: "blog-daleseo",
        name: "DaleSeo",
        type: "rss",
        group: "korean",
        url: "https://www.daleseo.com/rss.xml",
        weight: 6,
        language: "ko",
    },
    {
        id: "blog-evan-moon",
        name: "Evan Moon",
        type: "rss",
        group: "korean",
        url: "https://evan-moon.github.io/feed.xml",
        weight: 7,
        language: "ko",
    },
    {
        id: "blog-kciter",
        name: "kciter",
        type: "rss",
        group: "korean",
        url: "https://kciter.so/feed.xml",
        weight: 7,
        language: "ko",
    },

    /* ── 커뮤니티 ─────────────────────────────────────── */
    {
        id: "hackernews-top",
        name: "Hacker News",
        type: "hackernews",
        group: "community",
        url: "https://hacker-news.firebaseio.com/v0",
        weight: 9,
        language: "en",
    },
    {
        id: "github-trending",
        name: "GitHub Trending",
        type: "github-trending",
        group: "community",
        url: "https://github.com/trending?since=daily",
        weight: 7,
        language: "en",
    },
    {
        id: "geeknews",
        name: "GeekNews",
        type: "rss",
        group: "community",
        url: "https://news.hada.io/rss/news",
        weight: 9,
        language: "ko",
    },
    {
        id: "korean-fe-article",
        name: "Korean FE Article",
        type: "rss",
        group: "community",
        url: "https://kofearticle.substack.com/feed",
        weight: 8,
        language: "ko",
    },
    {
        id: "yozm-it",
        name: "요즘IT",
        type: "rss",
        group: "community",
        url: "https://yozm.wishket.com/magazine/feed/",
        weight: 7,
        language: "ko",
    },
    {
        id: "lobsters",
        name: "Lobste.rs",
        type: "rss",
        group: "community",
        url: "https://lobste.rs/rss",
        weight: 7,
        language: "en",
    },
    {
        id: "dev-to",
        name: "DEV Community",
        type: "rss",
        group: "community",
        url: "https://dev.to/feed",
        weight: 5,
        language: "en",
    },
    {
        id: "echo-js",
        name: "Echo JS",
        type: "rss",
        group: "community",
        url: "https://www.echojs.com/rss",
        weight: 5,
        language: "en",
    },
    {
        id: "velog-trending",
        name: "Velog 트렌딩",
        type: "rss",
        group: "community",
        url: "https://v2.velog.io/rss",
        weight: 5,
        language: "ko",
    },

    /* ── 뉴스레터·매거진 ──────────────────────────────── */
    {
        id: "this-week-in-react",
        name: "This Week In React",
        type: "rss",
        group: "newsletter",
        url: "https://substack.thisweekinreact.com/feed",
        weight: 9,
        language: "en",
    },
    {
        id: "javascript-weekly",
        name: "JavaScript Weekly",
        type: "rss",
        group: "newsletter",
        url: "https://javascriptweekly.com/rss",
        weight: 8,
        language: "en",
    },
    {
        id: "total-typescript",
        name: "Total TypeScript",
        type: "rss",
        group: "newsletter",
        url: "https://www.totaltypescript.com/rss.xml",
        weight: 8,
        language: "en",
    },
    {
        id: "frontend-focus",
        name: "Frontend Focus",
        type: "rss",
        group: "newsletter",
        url: "https://frontendfoc.us/rss",
        weight: 7,
        language: "en",
    },
    {
        id: "smashing-magazine",
        name: "Smashing Magazine",
        type: "rss",
        group: "newsletter",
        url: "https://www.smashingmagazine.com/feed/",
        weight: 7,
        language: "en",
    },
    {
        id: "tldr",
        name: "TLDR",
        type: "rss",
        group: "newsletter",
        url: "https://tldr.tech/api/rss/tech",
        weight: 7,
        language: "en",
    },
    {
        id: "node-weekly",
        name: "Node Weekly",
        type: "rss",
        group: "newsletter",
        url: "https://nodeweekly.com/rss",
        weight: 6,
        language: "en",
    },
    {
        id: "css-weekly",
        name: "CSS Weekly",
        type: "rss",
        group: "newsletter",
        url: "https://feeds.feedburner.com/CSS-Weekly",
        weight: 6,
        language: "en",
    },
    {
        id: "css-tricks",
        name: "CSS-Tricks",
        type: "rss",
        group: "newsletter",
        url: "https://css-tricks.com/feed/",
        weight: 6,
        language: "en",
    },
];

export const getSourceById = (id: string): NewsSource | undefined =>
    NEWS_SOURCES.find((source) => source.id === id);
