export const ROUTES = {
    HOME: "/",
    POSTS: "/posts",
    POST: (slug: string) => `/posts/${slug}`,
    POSTS_WITH_CATEGORY: (category: string) => `/posts?category=${category}`,
    POSTS_WITH_TAG: (tag: string) => `/posts?tag=${tag}`,
    ARCHIVING: "/archiving",
    ARCHIVING_DETAIL: (slug: string) => `/archiving/${slug}`,
    NEWS: "/news",
    NEWS_DETAIL: (date: string) => `/news/${date}`,
    STOCKS: "/stocks",
    TOOLS: "/tools",
    TOOLS_TIMESTAMP: "/tools/timestamp-converter",
    TOOLS_UUID: "/tools/uuid-generator",
    TOOLS_JSON: "/tools/json-formatter",
    TOOLS_JWT: "/tools/jwt-decoder",
    TOOLS_BASE64: "/tools/base64-url",
    FOOD: "/food",
    ABOUT: "/about-me",
} as const;
